In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os
import json

In [2]:

# posterior 1 data
filename_posterior_1 =  "./posterior_condition_1_slope_gempy_50.0_scale_10.0/MAP/gmm_data.json"
# Open and read the JSON file
with open(filename_posterior_1, 'r') as file:
    data_1 = json.load(file)

# Now `data` is a Python dictionary containing the parsed JSON
print(data_1)

{'weights': [0.17222122950524524, 0.16657030930015826, 0.30008931481578, 0.12778673071055763, 0.1555510968643503, 0.07778131880390858], 'means': [[6.852103167220808, -0.6535951767458951, 0.29128702798577016, -0.03714358078103068, -0.0016505484425937695, 0.008086692345906808, -0.00887709553987681, 0.0017631315453050778], [-4.115131584321111, -0.5195796984620951, 0.17419422758328912, 0.2227644905360674, 0.0424204932836515, 0.0005248724352387649, 0.007842825327187358, 0.008827452998416856], [-3.242594000103213, -0.2072522834384927, -0.08645831733094834, -0.14015077859989683, -0.04464219907390589, -0.006979381724853593, -0.00227062983164005, -0.008719513644134496], [0.690903671449064, 0.5551516024833401, -0.56814048334023, -0.038490146370797354, 0.06463580932030204, 0.005459815834301243, -0.004630608313255808, 0.01516008513708653], [2.8731820316988763, 0.5029057474297364, -0.4096323919490869, 0.11084737431081142, -0.012250051522096402, -0.0010139249074293318, 0.013971393125413508, -0.00666

In [3]:
gmm_data_init = "./posterior_condition_1_slope_gempy_50.0_scale_10.0/initial_gmm_data.json"
with open(gmm_data_init, 'r') as file:
    gmm_data_ = json.load(file)

# Now `data` is a Python dictionary containing the parsed JSON
print(gmm_data_)

{'weights': [0.0888888888888889, 0.19444444444444445, 0.32777777777784467, 0.138888888888822, 0.07777777777777779, 0.17222222222222225], 'means': [[3.7208996115348816, 0.4621365986770504, -0.38325648590917505, 0.1339713469334279, -0.031003612809262088, -0.08185870876962512, 0.06337077945924197, -0.01746707796383494], [1.0519160847118585, 0.555912691358434, -0.5259137482608656, 0.0021489815856467003, 0.046855723845825585, 0.040198721617149116, -0.020835183163250795, 0.012615022685919382], [-3.9209699509494302, -0.4431365976214542, 0.09577111273722402, 0.021118776743166538, 0.02599301077262914, -0.004097694782628327, 0.009631704356356515, 0.002086121122094764], [-2.6888362463945525, -0.025162621357115226, -0.20390677112655703, -0.08549317082194592, -0.10692849237370185, -0.004781174937722889, -0.018229813747233592, -0.013177204377722176], [-0.7301433867660423, 1.4417575425338933, 1.0683009108739074, -0.012548754425808922, 0.003354685593278349, 0.0009558767016774778, -0.008714975285858979

In [4]:
# posterior 3 data
filename_posterior_3_1 =  "./posterior_condition_3_alpha_1e-05_beta_1000.0_slope_gempy_50.0/MAP/gmm_data.json"
# Open and read the JSON file
with open(filename_posterior_3_1, 'r') as file:
    data_3_1 = json.load(file)

# Now `data` is a Python dictionary containing the parsed JSON
print(data_3_1)

{'weights': [0.1232475361107074, 0.19872769923325875, 0.2675575774329731, 0.13584013909550968, 0.0873946522946416, 0.18723239583290943], 'means': [[3.7248451564623166, 0.461485880168544, -0.3836587827714324, 0.13689090858975256, -0.030721325028934224, -0.0814818798813635, 0.06580625871144624, -0.017007030583383105], [1.0553709227858687, 0.5573527707803483, -0.5285041286428807, -0.0006766361262776382, 0.04734006596704152, 0.03973116962301835, -0.017058041424931968, 0.016620447851165527], [-3.921401327284026, -0.44362295603758606, 0.09599262831631501, 0.025632700726239504, 0.02836960161107313, -0.005840675403548437, 0.008113529871453098, 0.0016307156181803667], [-2.6828757644504786, -0.023292261936750734, -0.20477394772854876, -0.08588731724983362, -0.10774311006460535, -0.007497826047400979, -0.023045620041114816, -0.01878527484931704], [-0.730991876559597, 1.4437791583124455, 1.0725591436913868, -0.015792075046217793, 0.005634860614544859, 0.004919636135900012, -0.005722768344961195, -

In [5]:
# posterior 3 data
filename_posterior_3_2 =  "./posterior_condition_3_alpha_0.0001_beta_0.1_slope_gempy_50.0/MAP/gmm_data.json"
# Open and read the JSON file
with open(filename_posterior_3_2, 'r') as file:
    data_3_2 = json.load(file)

# Now `data` is a Python dictionary containing the parsed JSON
print(data_3_2)

{'weights': [0.17222189338818356, 0.1666707794935848, 0.26704423451332276, 0.1331055655344255, 0.1184297332096066, 0.14252779386087672], 'means': [[3.715452787898787, 0.46413400308961983, -0.3837994867158411, 0.1408857150449136, -0.041268382112672135, -0.08470195367518414, 0.06370259542777004, -0.012985742929229356], [1.0423715357293946, 0.5588593877284292, -0.5282128554217278, -0.002752809605171867, 0.047695048492535426, 0.03425517128268487, -0.020615933765228488, 0.013988839118251445], [-3.9082835270752767, -0.4367267355298251, 0.0941009385316082, 0.01776432811894863, 0.007105372094531486, -0.0009362473737350508, 0.011764790215084853, -0.0022511430105089476], [-2.6989167998381682, -0.025178303916309586, -0.1980518555560225, -0.08716921253584427, -0.1116349474493757, 0.0031644839997401726, -0.008550897272301197, -0.008893586244738875], [-0.7253289167494278, 1.4459436149432265, 1.0738204358805539, -0.009975283444534834, 0.0013604589019799798, 0.0023670348758200277, -0.00914078966801140

In [6]:
# posterior 3 data
filename_posterior_3_8 =  "./posterior_condition_3_alpha_1000000.0_beta_1000_slope_gempy_50.0/MAP/gmm_data.json"
# Open and read the JSON file
with open(filename_posterior_3_8, 'r') as file:
    data_3_8 = json.load(file)

# Now `data` is a Python dictionary containing the parsed JSON
print(data_3_8)

{'weights': [0.1593665920244475, 0.17418256804302296, 0.2891964821910339, 0.14392185374025576, 0.15555119030887402, 0.07778131369236577], 'means': [[3.728195517845301, 0.4667780040764613, -0.3836866910161931, 0.13156399452705764, -0.03388809901037677, -0.0851763763397403, 0.06723906998415792, -0.014183463002105214], [1.0267929144882495, 0.5572633807875571, -0.5333725647651965, 0.004646699080013541, 0.04916615143564825, 0.03316686227322126, -0.020015125599102956, 0.012410353241816215], [-3.8927925715996614, -0.42776288555030156, 0.08655548730129474, 0.002728938391735695, 0.02531221604929197, -0.009561348258684188, 0.01313200549125053, 0.012593682632692605], [-2.705606433970739, -0.031147824538615015, -0.20869753880888214, -0.08008699575653214, -0.11327049226981573, -0.0004088174887541157, -0.005599372114697454, -0.013715374421187287], [-0.7672664532352222, 1.4410619180502522, 1.0764321459295614, -0.008894892794914467, -0.010143482443148747, 0.0128064499076289, -0.00030430323598449905, -

In [7]:
# posterior 3 data
filename_posterior_3_9 =  "./posterior_condition_3_alpha_10000000.0_beta_1000.0_slope_gempy_50.0/MAP/gmm_data.json"
# Open and read the JSON file
with open(filename_posterior_3_9, 'r') as file:
    data_3_9 = json.load(file)

# Now `data` is a Python dictionary containing the parsed JSON
print(data_3_9)

{'weights': [0.14422660608529703, 0.17272775161406106, 0.3111904883042163, 0.10568182915731192, 0.08841155124122567, 0.17776177359788795], 'means': [[3.757947817711114, 0.46339055584639527, -0.36791184281517186, 0.12751982232978762, -0.029239323540820924, -0.08534475116228908, 0.0636066541308095, -0.012412510416327722], [1.099684372911254, 0.5616686885223342, -0.5105807124777447, 0.008235516261238742, 0.03922710854191914, 0.04555086122722006, -0.023638247911265575, 0.018021279020702267], [-3.883543089100734, -0.4276318420016207, 0.0793610541459223, -0.019643980504606716, 0.014466378987788069, -0.007914443362989637, 0.010286233790779331, 0.007297738384065271], [-2.6749780478571945, -0.022508154088121665, -0.21180290650975392, -0.07503568384283851, -0.10816534472286604, -0.013403646800367904, -0.020015773336899093, -0.007044301800970392], [-0.7263243140707492, 1.4485247594982258, 1.0819028442259457, -0.013613959433674298, 0.022007675822305006, -0.007670478468591624, -0.02587885647394376,

In [8]:
# posterior 3 data
filename_posterior_3_10 =  "./posterior_condition_3_alpha_1000000.0_beta_1000_slope_gempy_50.0/MAP/gmm_data.json"
# Open and read the JSON file
with open(filename_posterior_3_10, 'r') as file:
    data_3_10 = json.load(file)

# Now `data` is a Python dictionary containing the parsed JSON
print(data_3_10)

{'weights': [0.1593665920244475, 0.17418256804302296, 0.2891964821910339, 0.14392185374025576, 0.15555119030887402, 0.07778131369236577], 'means': [[3.728195517845301, 0.4667780040764613, -0.3836866910161931, 0.13156399452705764, -0.03388809901037677, -0.0851763763397403, 0.06723906998415792, -0.014183463002105214], [1.0267929144882495, 0.5572633807875571, -0.5333725647651965, 0.004646699080013541, 0.04916615143564825, 0.03316686227322126, -0.020015125599102956, 0.012410353241816215], [-3.8927925715996614, -0.42776288555030156, 0.08655548730129474, 0.002728938391735695, 0.02531221604929197, -0.009561348258684188, 0.01313200549125053, 0.012593682632692605], [-2.705606433970739, -0.031147824538615015, -0.20869753880888214, -0.08008699575653214, -0.11327049226981573, -0.0004088174887541157, -0.005599372114697454, -0.013715374421187287], [-0.7672664532352222, 1.4410619180502522, 1.0764321459295614, -0.008894892794914467, -0.010143482443148747, 0.0128064499076289, -0.00030430323598449905, -

In [9]:
np.array(data_3_10["means"]).shape, np.array(data_3_9["means"]).shape

((6, 8), (6, 8))

In [10]:
np.sqrt(np.sum((np.array(data_3_10["means"]) - np.array(data_3_9["means"]))**2, axis=1))

array([0.03463879, 0.07849635, 0.02818452, 0.03866736, 0.06889967,
       0.02292616])

In [11]:
def euclidean_distance(arr_1, arr_2):
    delta = arr_1 - arr_2
    sq_delta = delta**2
    sum_sq_delta = np.sum(sq_delta, axis=1)
    return np.sqrt(sum_sq_delta)

In [12]:
euclidean_distance(np.array(data_3_10["means"]), np.array(gmm_data_["means"]))

array([0.01121723, 0.02739288, 0.04007999, 0.02425688, 0.04352005,
       0.01119366])

In [13]:
euclidean_distance(np.array(data_3_10["means"]), np.array(data_1["means"]))

array([3.3932097 , 5.30557298, 0.72617028, 3.47037134, 4.04427098,
       7.90976862])

In [14]:
euclidean_distance(np.array(data_3_1["means"]), np.array(gmm_data_["means"]))

array([0.00557147, 0.00771151, 0.00566089, 0.01013011, 0.00855349,
       0.00314612])

In [15]:
euclidean_distance(np.array(data_3_1["means"]), np.array(data_1["means"]))

array([3.39467021, 5.33290097, 0.7635247 , 3.44712061, 4.01110862,
       7.9039281 ])

In [16]:
euclidean_distance(np.array(data_3_1["means"]), np.array(data_3_10["means"]))

array([0.01006536, 0.03068622, 0.04303728, 0.03222286, 0.0416867 ,
       0.01187336])